server:
  port: 8081

spring:
  application:
    name: jet

  datasource:
    url: jdbc:mariadb://localhost:3306/java_expense_tracker?createDatabaseIfNotExist=true&autoReconnect=true&useSLL=false
    username: root
    password: Password123!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false

logging:
  level:
    com.mailgun: trace
    it.cgmconsulting.myblog: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info